language: android

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS=-Xms128m
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - PATH=$PATH:/usr/local/android-sdk/tools/bin:/usr/local/android-sdk/build-tools/29.0.2

android:
  components:
    - tools
    - tools # Repeated to force updated version. See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - build-tools-29.0.2
    - android-29
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
