language: android

jdk:
  - oraclejdk8

env:
  global:
    - GRADLE_OPTS=-Xms128m
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - PATH=$PATH:/usr/local/android-sdk/build-tools/25.0.2

before_install:
  - gem install fastlane -v 2.53.1 --no-rdoc --no-ri --no-document
  - gem install supply -v 1.0.0 --no-rdoc --no-ri --no-document

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25

script: ./gradlew test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
